### ISSUE TITLE
Exclude unloaded tabs

### ISSUE THREAD

**Issue by noscript** [mikedeboer/soundcloud-player#2]
As it seems, the player looks for the first tab with sound cloud. Would it be possible to exclude unloaded tabs? To distinguish such I have this style in Stylish:

``` css
.tabbrowser-tab[pending] {
    opacity:0.5 !important;
}
```
